name: validator_dart
description: Pure dart library to validate and sanitize data
version: 0.1.0
homepage: https://github.com/AlmisSolutions/validator_dart

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.17.0
